repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10  # Use the latest stable version
    hooks:
    -   id: ruff
        args: [--fix, --config, pyproject.toml]
        files: ^.*\.py$
    # Run the formatter.
    - id: ruff-format
