repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest stable version
    hooks:
    -   id: black
        files: ^.*\.py$

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0  # Use the latest stable version
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^.*\.py$
