site_name: LblProf
site_description: Line by line terminal based profiler
theme:
  name: mkdocs
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Documentation: documentation.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences 