[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lblprof"
version = "0.1.8"
description = "Line by line terminal based profiler"
authors = [{ name = "le-codeur-rapide", email = "paul.vezia@gmail.com" }]
readme = "Readme.md"
requires-python = ">=3.12"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "matplotlib>=3.10.1",
    "virtualenv>=20.30.0",
    "pandas>=2.0.3",
    "chromadb>=0.5.23",
    "ruff>=0.3.0",
    "pytest>=7.0.0",
    "black>=24.2.0",
    "pydantic>=2.0.0",
]

[tool.setuptools]
packages = ["lblprof"]

[tool.pytest.ini_options]
testpaths = ["lblprof/tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
log_cli = true
log_cli_level = "INFO"
addopts = "-v -x"

[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "F", # pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    # "C90",  # mccabe complexity
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "ANN", # type annotations
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "EM",  # flake8-errmsg
    "EXE", # flake8-executable
    "FA",  # flake8-future-annotations
    # "FBT", # flake8-boolean-trap
    "ICN", # flake8-import-conventions
    "ISC", # flake8-implicit-str-concat
    "PIE", # flake8-pie
    "PT",  # flake8-pytest-style
    "PTH", # flake8-use-pathlib
    "RET", # flake8-return
    "RSE", # flake8-raise
    "SIM", # flake8-simplify
    "S",   # flake8-bandit
    "T20", # flake8-print
    "ARG", # flake8-unused-arguments
    "ERA", # eradicate
    # "PL",   # pylint
    "PERF", # perflint
    "FURB", # refurb
    "TRY",  # tryceratops
]

[tool.ruff.lint.per-file-ignores]
"**/*.py" = ["S311", "S603"]
"lblprof/tests/**/*.py" = [
    "ANN",
    "B",
    "S101",
    "EM",
    "LOG015",
    "G",
    "T20",
    "S",
    "PTH",
    "TRY",
]
